
/*
 * action types
 */
export const GET_QUERY_STRING = 'GET_QUERY_STRING';
export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
export const REMOVE_PRODUCT_FROM_WISHLIST = 'REMOVE_PRODUCT_FROM_WISHLIST';
export const RESET_TO_INITIAL_STATE = 'RESET_TO_INITIAL_STATE';

